import { CorridorMetrics, generateMockCorridorData } from "../../lib/api";

export const mockCorridors: CorridorMetrics[] = [
  // USDC corridors (Major stablecoin - high volume)
  {
    ...generateMockCorridorData("USDC-EUR").corridor,
    id: "USDC-EUR",
    source_asset: "USDC",
    destination_asset: "EUR",
    success_rate: 97.8,
    total_attempts: 3200,
    successful_payments: 3130,
    failed_payments: 70,
    average_latency_ms: 380,
    median_latency_ms: 280,
    p95_latency_ms: 950,
    p99_latency_ms: 1500,
    liquidity_depth_usd: 12000000,
    liquidity_volume_24h_usd: 2500000,
    liquidity_trend: "increasing",
    health_score: 98,
  },
  {
    ...generateMockCorridorData("USDC-GBP").corridor,
    id: "USDC-GBP",
    source_asset: "USDC",
    destination_asset: "GBP",
    success_rate: 94.1,
    total_attempts: 2450,
    successful_payments: 2305,
    failed_payments: 145,
    average_latency_ms: 410,
    median_latency_ms: 310,
    p95_latency_ms: 1050,
    p99_latency_ms: 1700,
    liquidity_depth_usd: 9800000,
    liquidity_volume_24h_usd: 1800000,
    liquidity_trend: "stable",
    health_score: 91,
  },
  {
    ...generateMockCorridorData("USDC-JPY").corridor,
    id: "USDC-JPY",
    source_asset: "USDC",
    destination_asset: "JPY",
    success_rate: 92.5,
    total_attempts: 2800,
    successful_payments: 2590,
    failed_payments: 210,
    average_latency_ms: 425,
    median_latency_ms: 315,
    p95_latency_ms: 1080,
    p99_latency_ms: 1650,
    liquidity_depth_usd: 8200000,
    liquidity_volume_24h_usd: 1600000,
    liquidity_trend: "stable",
    health_score: 89,
  },
  {
    ...generateMockCorridorData("USDC-PHP").corridor,
    id: "USDC-PHP",
    source_asset: "USDC",
    destination_asset: "PHP",
    success_rate: 86.3,
    total_attempts: 1500,
    successful_payments: 1295,
    failed_payments: 205,
    average_latency_ms: 580,
    median_latency_ms: 450,
    p95_latency_ms: 1400,
    p99_latency_ms: 2100,
    liquidity_depth_usd: 4200000,
    liquidity_volume_24h_usd: 720000,
    liquidity_trend: "increasing",
    health_score: 78,
  },
  {
    ...generateMockCorridorData("USDC-CAD").corridor,
    id: "USDC-CAD",
    source_asset: "USDC",
    destination_asset: "CAD",
    success_rate: 95.5,
    total_attempts: 1800,
    successful_payments: 1719,
    failed_payments: 81,
    average_latency_ms: 400,
    median_latency_ms: 300,
    p95_latency_ms: 1000,
    p99_latency_ms: 1600,
    liquidity_depth_usd: 6500000,
    liquidity_volume_24h_usd: 950000,
    liquidity_trend: "stable",
    health_score: 93,
  },
  {
    ...generateMockCorridorData("USDC-AUD").corridor,
    id: "USDC-AUD",
    source_asset: "USDC",
    destination_asset: "AUD",
    success_rate: 96.2,
    total_attempts: 2200,
    successful_payments: 2116,
    failed_payments: 84,
    average_latency_ms: 390,
    median_latency_ms: 290,
    p95_latency_ms: 980,
    p99_latency_ms: 1550,
    liquidity_depth_usd: 7200000,
    liquidity_volume_24h_usd: 1200000,
    liquidity_trend: "increasing",
    health_score: 95,
  },

  // EUR corridors (Strong European market)
  {
    ...generateMockCorridorData("EUR-USDC").corridor,
    id: "EUR-USDC",
    source_asset: "EUR",
    destination_asset: "USDC",
    success_rate: 96.8,
    health_score: 96,
    liquidity_depth_usd: 11500000,
    liquidity_volume_24h_usd: 2300000,
    average_latency_ms: 370,
    median_latency_ms: 275,
    p95_latency_ms: 940,
    p99_latency_ms: 1480,
    total_attempts: 3100,
    successful_payments: 3001,
    failed_payments: 99,
    liquidity_trend: "increasing",
  },
  {
    ...generateMockCorridorData("EUR-GBP").corridor,
    id: "EUR-GBP",
    source_asset: "EUR",
    destination_asset: "GBP",
    success_rate: 96.5,
    health_score: 94,
    liquidity_depth_usd: 5500000,
    liquidity_volume_24h_usd: 980000,
    average_latency_ms: 390,
    median_latency_ms: 290,
    p95_latency_ms: 980,
    p99_latency_ms: 1520,
    total_attempts: 1800,
    successful_payments: 1737,
    failed_payments: 63,
    liquidity_trend: "stable",
  },
  {
    ...generateMockCorridorData("EUR-JPY").corridor,
    id: "EUR-JPY",
    source_asset: "EUR",
    destination_asset: "JPY",
    success_rate: 91.2,
    health_score: 87,
    liquidity_depth_usd: 6200000,
    liquidity_volume_24h_usd: 1100000,
    average_latency_ms: 445,
    median_latency_ms: 335,
    p95_latency_ms: 1120,
    p99_latency_ms: 1720,
    total_attempts: 2200,
    successful_payments: 2006,
    failed_payments: 194,
    liquidity_trend: "stable",
  },
  {
    ...generateMockCorridorData("EUR-PHP").corridor,
    id: "EUR-PHP",
    source_asset: "EUR",
    destination_asset: "PHP",
    success_rate: 84.7,
    health_score: 76,
    liquidity_depth_usd: 3100000,
    liquidity_volume_24h_usd: 520000,
    average_latency_ms: 595,
    median_latency_ms: 465,
    p95_latency_ms: 1450,
    p99_latency_ms: 2150,
    total_attempts: 1300,
    successful_payments: 1101,
    failed_payments: 199,
    liquidity_trend: "decreasing",
  },

  // GBP corridors (UK market)
  {
    ...generateMockCorridorData("GBP-USDC").corridor,
    id: "GBP-USDC",
    source_asset: "GBP",
    destination_asset: "USDC",
    success_rate: 95.1,
    health_score: 92,
    liquidity_depth_usd: 9200000,
    liquidity_volume_24h_usd: 1700000,
    average_latency_ms: 405,
    median_latency_ms: 305,
    p95_latency_ms: 1030,
    p99_latency_ms: 1680,
    total_attempts: 2350,
    successful_payments: 2234,
    failed_payments: 116,
    liquidity_trend: "stable",
  },
  {
    ...generateMockCorridorData("GBP-EUR").corridor,
    id: "GBP-EUR",
    source_asset: "GBP",
    destination_asset: "EUR",
    success_rate: 95.8,
    health_score: 93,
    liquidity_depth_usd: 7200000,
    liquidity_volume_24h_usd: 1400000,
    average_latency_ms: 410,
    median_latency_ms: 310,
    p95_latency_ms: 1040,
    p99_latency_ms: 1690,
    total_attempts: 2100,
    successful_payments: 2012,
    failed_payments: 88,
    liquidity_trend: "increasing",
  },
  {
    ...generateMockCorridorData("GBP-JPY").corridor,
    id: "GBP-JPY",
    source_asset: "GBP",
    destination_asset: "JPY",
    success_rate: 89.4,
    health_score: 84,
    liquidity_depth_usd: 4800000,
    liquidity_volume_24h_usd: 820000,
    average_latency_ms: 485,
    median_latency_ms: 375,
    p95_latency_ms: 1220,
    p99_latency_ms: 1880,
    total_attempts: 1700,
    successful_payments: 1520,
    failed_payments: 180,
    liquidity_trend: "stable",
  },

  // JPY corridors (Asian market)
  {
    ...generateMockCorridorData("JPY-USDC").corridor,
    id: "JPY-USDC",
    source_asset: "JPY",
    destination_asset: "USDC",
    success_rate: 93.4,
    health_score: 89,
    liquidity_depth_usd: 6800000,
    liquidity_volume_24h_usd: 1100000,
    average_latency_ms: 450,
    median_latency_ms: 340,
    p95_latency_ms: 1140,
    p99_latency_ms: 1750,
    total_attempts: 1900,
    successful_payments: 1775,
    failed_payments: 125,
    liquidity_trend: "increasing",
  },
  {
    ...generateMockCorridorData("JPY-EUR").corridor,
    id: "JPY-EUR",
    source_asset: "JPY",
    destination_asset: "EUR",
    success_rate: 90.6,
    health_score: 86,
    liquidity_depth_usd: 5900000,
    liquidity_volume_24h_usd: 950000,
    average_latency_ms: 465,
    median_latency_ms: 355,
    p95_latency_ms: 1180,
    p99_latency_ms: 1810,
    total_attempts: 1850,
    successful_payments: 1676,
    failed_payments: 174,
    liquidity_trend: "stable",
  },
  {
    ...generateMockCorridorData("JPY-GBP").corridor,
    id: "JPY-GBP",
    source_asset: "JPY",
    destination_asset: "GBP",
    success_rate: 88.9,
    health_score: 83,
    liquidity_depth_usd: 4500000,
    liquidity_volume_24h_usd: 750000,
    average_latency_ms: 495,
    median_latency_ms: 385,
    p95_latency_ms: 1250,
    p99_latency_ms: 1920,
    total_attempts: 1600,
    successful_payments: 1422,
    failed_payments: 178,
    liquidity_trend: "decreasing",
  },
  {
    ...generateMockCorridorData("JPY-PHP").corridor,
    id: "JPY-PHP",
    source_asset: "JPY",
    destination_asset: "PHP",
    success_rate: 82.1,
    health_score: 73,
    liquidity_depth_usd: 2800000,
    liquidity_volume_24h_usd: 450000,
    average_latency_ms: 615,
    median_latency_ms: 495,
    p95_latency_ms: 1520,
    p99_latency_ms: 2280,
    total_attempts: 1200,
    successful_payments: 985,
    failed_payments: 215,
    liquidity_trend: "stable",
  },

  // PHP corridors (Emerging market - lower reliability)
  {
    ...generateMockCorridorData("PHP-USDC").corridor,
    id: "PHP-USDC",
    source_asset: "PHP",
    destination_asset: "USDC",
    success_rate: 88.6,
    health_score: 82,
    liquidity_depth_usd: 3200000,
    liquidity_volume_24h_usd: 560000,
    average_latency_ms: 520,
    median_latency_ms: 410,
    p95_latency_ms: 1320,
    p99_latency_ms: 2020,
    total_attempts: 1400,
    successful_payments: 1240,
    failed_payments: 160,
    liquidity_trend: "increasing",
  },
  {
    ...generateMockCorridorData("PHP-EUR").corridor,
    id: "PHP-EUR",
    source_asset: "PHP",
    destination_asset: "EUR",
    success_rate: 83.2,
    health_score: 75,
    liquidity_depth_usd: 2700000,
    liquidity_volume_24h_usd: 440000,
    average_latency_ms: 605,
    median_latency_ms: 485,
    p95_latency_ms: 1480,
    p99_latency_ms: 2220,
    total_attempts: 1150,
    successful_payments: 957,
    failed_payments: 193,
    liquidity_trend: "stable",
  },
  {
    ...generateMockCorridorData("PHP-JPY").corridor,
    id: "PHP-JPY",
    source_asset: "PHP",
    destination_asset: "JPY",
    success_rate: 80.5,
    health_score: 71,
    liquidity_depth_usd: 2200000,
    liquidity_volume_24h_usd: 360000,
    average_latency_ms: 635,
    median_latency_ms: 515,
    p95_latency_ms: 1580,
    p99_latency_ms: 2380,
    total_attempts: 1000,
    successful_payments: 805,
    failed_payments: 195,
    liquidity_trend: "decreasing",
  },

  // CAD corridors (Canadian market)
  {
    ...generateMockCorridorData("CAD-USD").corridor,
    id: "CAD-USD",
    source_asset: "CAD",
    destination_asset: "USD",
    success_rate: 92.1,
    health_score: 88,
    liquidity_depth_usd: 4100000,
    liquidity_volume_24h_usd: 780000,
    average_latency_ms: 480,
    median_latency_ms: 370,
    p95_latency_ms: 1200,
    p99_latency_ms: 1850,
    total_attempts: 1600,
    successful_payments: 1475,
    failed_payments: 125,
    liquidity_trend: "stable",
  },

  // AUD corridors (Australian market)
  {
    ...generateMockCorridorData("AUD-USD").corridor,
    id: "AUD-USD",
    source_asset: "AUD",
    destination_asset: "USD",
    success_rate: 93.7,
    health_score: 90,
    liquidity_depth_usd: 5800000,
    liquidity_volume_24h_usd: 1020000,
    average_latency_ms: 460,
    median_latency_ms: 350,
    p95_latency_ms: 1160,
    p99_latency_ms: 1780,
    total_attempts: 1900,
    successful_payments: 1779,
    failed_payments: 121,
    liquidity_trend: "increasing",
  },
];