declare module "lucide-react" {
  import * as React from "react";

  type IconProps = React.SVGProps<SVGSVGElement> & {
    className?: string;
    title?: string;
    size?: number;
  };
  type IconComponent = React.FC<IconProps>;

  export const Info: IconComponent;
  export const Phone: IconComponent;
  export const BookOpen: IconComponent;
  export const X: IconComponent;
  export const Menu: IconComponent;
  export const Sun: IconComponent;
  export const Moon: IconComponent;
  export const Monitor: IconComponent;
  export const Bell: IconComponent;
  export const Settings: IconComponent;
  export const Wallet: IconComponent;
  export const WalletCards: IconComponent;
  export const CheckCircle: IconComponent;
  export const XCircle: IconComponent;
  export const PlusCircle: IconComponent;
  export const Trash2: IconComponent;
  export const ShieldCheck: IconComponent;
  export const Cpu: IconComponent;
  export const KeyRound: IconComponent;
  export const PenLine: IconComponent;
  export const Send: IconComponent;
  export const CheckCircle2: IconComponent;
  export const Copy: IconComponent;
  export const AlertCircle: IconComponent;
  export const AlertTriangle: IconComponent;
  export const Wifi: IconComponent;
  export const WifiOff: IconComponent;
  export const RotateCw: IconComponent;
  export const LogOut: IconComponent;
  export const Shield: IconComponent;
  export const ArrowUpRight: IconComponent;
  export const ArrowDownRight: IconComponent;
  export const TrendingUp: IconComponent;
  export const ChevronDown: IconComponent;
  export const Loader2: IconComponent;
  export const Share2: IconComponent;
  export const Hexagon: IconComponent;
  export const Activity: IconComponent;
  export const Zap: IconComponent;
  export const Server: IconComponent;
  export const ArrowLeft: IconComponent;
  export const Minus: IconComponent;
  export const TrendingDown: IconComponent;
  export const Home: IconComponent;
  export const Anchor: IconComponent;
  export const BarChart3: IconComponent;
  export const Compass: IconComponent;
  export const ChevronLeft: IconComponent;
  export const ChevronRight: IconComponent;
  export const LayoutDashboard: IconComponent;
  export const Waves: IconComponent;
  export const Droplets: IconComponent;
  export const Users: IconComponent;
  export const Database: IconComponent;
  export const Calculator: IconComponent;
  export const Key: IconComponent;
  export const Trophy: IconComponent;
  export const ScrollText: IconComponent;
  export const BellOff: IconComponent;
  export const Filter: IconComponent;
  export const Search: IconComponent;
  export const Calendar: IconComponent;
  export const Volume2: IconComponent;
  export const VolumeX: IconComponent;
  export const Smartphone: IconComponent;
  export const Save: IconComponent;
  export const RotateCcw: IconComponent;
  export const Clock: IconComponent;
  export const ArrowRight: IconComponent;
  export const MinusCircle: IconComponent;
  export const Building2: IconComponent;
  export const Globe: IconComponent;
  export const Mail: IconComponent;
  export const ExternalLink: IconComponent;
  export const RefreshCw: IconComponent;
  export const Banknote: IconComponent;
  export const Quote: IconComponent;
  export const ArrowDownToLine: IconComponent;
  export const ArrowUpFromLine: IconComponent;
  export const Download: IconComponent;
  export const ArrowUpDown: IconComponent;
  export const Maximize2: IconComponent;
  export const ArrowRightLeft: IconComponent;
  export const FileJson: IconComponent;
  export const FileText: IconComponent;
  export const Check: IconComponent;
  export const Plus: IconComponent;
  export const Github: IconComponent;
  export const Twitter: IconComponent;
  export const Loader2: IconComponent;
  export const ArrowDownToLine: IconComponent;

  const _default: { [key: string]: IconComponent };
  export default _default;
}
